server:
  port: 8083

spring:
  application:
    name: APIGATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCB
                fallbackUri: forward:/userFallback
            - name: Retry
              args:
                retries: 3
                backoff:
                  firstBackoff: 1s
                  maxBackoff: 1s
                  factor: 1
            - name: RateLimiter
              args:
                rate-limiter-name: userServiceRL
                fallbackUri: forward:/userFallback

        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**
          filters:
            - name: CircuitBreaker
              args:
                name: hotelServiceCB
                fallbackUri: forward:/hotelFallback
            - name: Retry
              args:
                retries: 3
                backoff:
                  firstBackoff: 1s
                  maxBackoff: 1s
                  factor: 1
            - name: RateLimiter
              args:
                rate-limiter-name: hotelServiceRL
                fallbackUri: forward:/hotelFallback

        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**
          filters:
            - name: CircuitBreaker
              args:
                name: ratingServiceCB
                fallbackUri: forward:/ratingFallback
            - name: Retry
              args:
                retries: 3
                backoff:
                  firstBackoff: 1s
                  maxBackoff: 1s
                  factor: 1
            - name: RateLimiter
              args:
                rate-limiter-name: ratingServiceRL
                fallbackUri: forward:/ratingFallback

eureka:
  instance:
    appname: API-GATEWAY
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
    instances:
      userServiceCB:
        baseConfig: default
      hotelServiceCB:
        baseConfig: default
      ratingServiceCB:
        baseConfig: default

  ratelimiter:
    instances:
      userServiceRL:
        limit-for-period: 5        # max 5 requests per period
        limit-refresh-period: 1s   # period duration
        timeout-duration: 0        # fail fast if exceeded
      hotelServiceRL:
        limit-for-period: 5
        limit-refresh-period: 1s
        timeout-duration: 0
      ratingServiceRL:
        limit-for-period: 5
        limit-refresh-period: 1s
        timeout-duration: 0
