server:
  port: 8083

spring:
  application:
    name: APIGATEWAY
  redis:
    url: "redis://:dBo6F6eELkzNaIH3F6OUHKhNSwDGkNub@redis-17389.c301.ap-south-1-1.ec2.redns.redis-cloud.com:17389"
  

  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 20    # tokens per second
            redis-rate-limiter.burstCapacity: 10    # max tokens
            redis-rate-limiter.requestedTokens: 1
            key-resolver: "#{@ipKeyResolver}"       # added key resolver

      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCB
                fallbackUri: forward:/userFallback
            - name: Retry
              args:
                retries: 3
                backoff:
                  firstBackoff: 1s
                  maxBackoff: 1s
                  factor: 1

        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**
          filters:
            - name: CircuitBreaker
              args:
                name: hotelServiceCB
                fallbackUri: forward:/hotelFallback
            - name: Retry
              args:
                retries: 3
                backoff:
                  firstBackoff: 1s
                  maxBackoff: 1s
                  factor: 1

        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**
          filters:
            - name: CircuitBreaker
              args:
                name: ratingServiceCB
                fallbackUri: forward:/ratingFallback
            - name: Retry
              args:
                retries: 3
                backoff:
                  firstBackoff: 1s
                  maxBackoff: 1s
                  factor: 1

eureka:
  instance:
    appname: API-GATEWAY
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
    instances:
      userServiceCB:
        baseConfig: default
      hotelServiceCB:
        baseConfig: default
      ratingServiceCB:
        baseConfig: default
