spring:
  data:
    mongodb:
      uri: mongodb+srv://gourraj548:Rajgour1000@journalapp.yrpmctd.mongodb.net/?retryWrites=true&w=majority&appName=journalApp
      database: hotelratingsdb
      auto-index-creation: true
  application:
    name: RATINGSERVICE

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
